[tool.poetry]
name = "hometask4"
version = "0.1.0"
description = "HT4"
authors = ["BGU"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
